title: kai mashimo
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  UNSW, Sydney
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kaimashimo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

buttons:
  show_resume: false
  show_portfolio: true
  show_blog: true
  show_home: false
  show_fr: false
  show_en: false

plugins:
  - jekyll-feed

github:
  is_project_page: false



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
